### ISSUE TITLE
branch discussion

### ISSUE THREAD

**Issue by HowDoIUseGit** [SE-TINF22B6/for-all-teams#39]
## manage branches
# To-do list, if necessary:
1. [ ] create a new branch for each head topic (frontend, backend, ...)
2. [ ] block easy main push/merge rights
3. [ ] discuss develop style --> does every new feature require a new subbranch?

**Comment by HowDoIUseGit** [comment]
1 person required for merges/pushes
headbranches --> frontend/backend
subbranches for each action like bugfixes, new features, etc...
